### ISSUE TITLE
Use GitHub Pages for hosting

### ISSUE THREAD

**Issue by MichaelChan-Pong** [CatholicGators/CatholicGatorsAdminApp#60]
Currently, we serve the page from a DigitalOcean server. This does not scale and may be overwhelmed. I propose we use GitHub Pages instead. The pipeline would be as following:

- Transpile and generate new static pages
- Change branches to hosting branch
- Remove .gitignore
- Delete everything except the pages
- Force push to hosting branch

**Comment by joeySchentrup** [comment]
Moved to free firebase hosting.
